export const AGENT_REQUIRED =
    "REFUSED  Every command needs --agent <LETTER>. The tool uses the letter to find your record, to show you " +
    "what changed since your last read, and to decide which items are addressed to you.\n";

export const waitHelp = function waitHelp(command: string): string {
    return [
        `${command} -- --agent <LETTER> [flags]`,
        "",
        "  Writes to a coordination surface and then waits for the next write by another seat, in one call.",
        "",
        "  Required on every call",
        "  --agent <LETTER>        The seat this call writes and reads as.",
        "",
        "  Posting",
        "  --item <TEXT>           Add an item to your record, then wait. Needs --kind. Pass - to read the text",
        "                          from standard input, which keeps quotes and apostrophes intact.",
        "  --item-file <PATH>      The same, with the text read from a file.",
        "  --kind <KIND>           Required with --item: artifact (asks for something to be made; closes with a",
        "                          reference to it) or judgement (asks for a reading; closes when acknowledged).",
        "  --field <NAME>          Rewrite a field in your own record. Needs --value. Refuses a field the record",
        "                          does not have.",
        "  --value <TEXT>          Required with --field. The field's new text.",
        "  --record                Add your record to the surface named by --file. Its fields come from that",
        "                          surface's template.",
        "  --file <PATH>           Write to another surface, by path or by name. Defaults to the board. Post to a",
        "                          venue with --file <venue> --item.",
        "",
        "  Closing and removing",
        "  --closes <ID>           Close an item addressed to you. An item's author cannot close it.",
        "  --ref <KIND:MEMBER>     Required when closing an artifact item, refused for a judgement item: the history",
        "                          entry the item's content was extracted to.",
        "  --mark <ID>             Record that you have read an item. An item addressed to several seats is removed",
        "                          when its last active reader marks it.",
        "  --compress <LABEL>      Remove the field with this label from your own record.",
        "  --discharge <CLAUSE>    Remove a directive from a venue once it has been carried out. Needs --ref.",
        "  A venue keeps every position while it is open: --closes and --compress are refused there, and the",
        "  venue moves whole to the archive when it converges. The board is cleared as items are handled.",
        "",
        "  Venues",
        "  --read                  Mark that you have read the venue named by --file.",
        "  --sign <TEXT>           Sign the venue named by --file. Refused while your record states a need.",
        "  --raise <INVARIANT>     Create the venue for a planned agenda row. Without a value, the first planned",
        "                          row is created.",
        "  --seats <LETTERS>       The seats a raised venue includes, separated by commas or spaces. Each must have",
        "                          a row in the agent index. Defaults to the active seats.",
        "  --defer <CLAUSE>        Record a question this venue leaves open. Needs --to.",
        "  --to <RECEIVER>         Required with --defer: the venue, seat or planned agenda row that receives it.",
        "  --arrive                Carry the deferred questions of the venue named by --file into its successor.",
        "",
        "  History and planning",
        "  --extract <HEADING>     Add an entry to the history file. Needs --body or --body-file.",
        "  --append <HEADING>      Extend a clause of an existing history entry. Needs --lead and a body.",
        "  --lead <LEAD>           Required with --append: which clause to extend.",
        "  --body <TEXT>           The entry text. Pass - to read it from standard input.",
        "  --body-file <PATH>      The entry text, read from a file.",
        "  --agenda <NAME>         Add a planned row to the agenda. Needs --establishes; --planned sets its position",
        "                          and --because adds a note.",
        "  --member <HEADING>      Add a member to the surface named by --file, below its declared member region.",
        "",
        "  Seats and surfaces",
        "  --index <ROLE>          Claim the next free letter in the agent index for a role. Do this before your",
        "                          first write anywhere else.",
        "  --transition <STATE>    Change your own state in the agent index.",
        "  --role <CONCERN>        Create your role document, with its sections empty.",
        "  --model <SUBJECT>       Create a model surface: what a construct is.",
        "  --finding <SUBJECT>     Create a finding surface: one measured row per claim.",
        "  --distribute <SUBJECT>  Create a planning surface: one item per piece of work, with its owner. A venue",
        "                          cannot converge without one.",
        "",
        "  Running",
        "  --barrier               Take the exclusive-write barrier before acting.",
        "  --no-wait               Act and return without waiting.",
        "  --rehearse              Check every argument and write nothing. Surface creation also runs its own",
        "                          refusals; other commands stop before their own refusals run.",
        "  --help                  This text. Needs no --agent.",
        "",
        "  Exit codes: 0 changed or acted · 1 quiet · 2 refused · 3 blocked (every other seat is waiting, so",
        "  post before you wait).",
        "",
        "  A wait that returns CHANGED shows every write by another seat since your last read. Act on it before",
        "  you wait again.",
        "",
    ].join("\n");
};
