import type { DocForm } from "#types/location.types";

const AI_CONTEXT_FORM: DocForm = { boundary: true, folder: "", id: "ai-context", kind: "authored", ownerAxis: "none" };

export const DOC_FORMS: Readonly<Record<string, DocForm>> = {
    changelog: { boundary: false, folder: "changelogs", id: "changelog", kind: "authored", ownerAxis: "module" },
    checklist: {
        boundary: false,
        folder: "checklists",
        id: "checklist",
        kind: "authored",
        mood: "directive",
        ownerAxis: "concern",
        tag: "checklist",
    },
    contract: {
        boundary: false,
        folder: "contracts",
        id: "contract",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "contract",
    },
    design: {
        boundary: false,
        folder: "designs",
        id: "design",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "design",
    },
    example: {
        boundary: false,
        folder: "examples",
        id: "example",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "example",
    },
    guide: {
        boundary: false,
        folder: "guides",
        id: "guide",
        kind: "authored",
        mood: "directive",
        ownerAxis: "concern",
        tag: "guide",
    },
    note: {
        boundary: false,
        folder: "notes",
        id: "note",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "note",
    },
    plan: {
        boundary: false,
        folder: "plans",
        id: "plan",
        kind: "authored",
        mood: "directive",
        ownerAxis: "concern",
        tag: "plan",
    },
    protocol: {
        boundary: false,
        folder: "protocols",
        id: "protocol",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "protocol",
    },
    readme: { boundary: true, folder: "", id: "readme", kind: "authored", ownerAxis: "none" },
    reference: {
        boundary: false,
        folder: "references",
        id: "reference",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "reference",
    },
    research: {
        boundary: false,
        folder: "research",
        id: "research",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "research",
    },
    spec: {
        boundary: false,
        folder: "specs",
        id: "spec",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "spec",
    },
    taxonomy: {
        boundary: false,
        folder: "taxonomy",
        id: "taxonomy",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "concern",
        tag: "taxonomy",
    },
    template: {
        boundary: false,
        folder: "templates",
        id: "template",
        kind: "authored",
        mood: "declarative",
        ownerAxis: "none",
        tag: "template",
    },
    [AI_CONTEXT_FORM.id]: AI_CONTEXT_FORM,
};
