export const BANNED_TERMS: readonly string[] = [
    "previously",
    "formerly",
    "originally",
    "no longer",
    "used to",
    "renamed from",
    "migrated from",
    "moved from",
    "replaced by",
    "was replaced",
    "has been replaced",
    "historically",
    "in the past",
    "back when",
    "once was",
    "earlier version",
    "prior version",
    "old version",
    "the old",
    "changed from",
    "revision history",
    "instead of the old",
    "to be removed",
    "will be removed",
    "phased out",
];
