export const GO_KEYWORDS: ReadonlySet<string> = new Set([
    "func",
    "if",
    "for",
    "switch",
    "select",
    "return",
    "go",
    "defer",
    "range",
    "case",
    "else",
    "type",
    "var",
    "const",
    "package",
    "import",
    "map",
    "chan",
    "struct",
    "interface",
    "break",
    "continue",
    "goto",
]);

export const GO_BUILTINS: ReadonlySet<string> = new Set([
    "make",
    "len",
    "cap",
    "append",
    "new",
    "delete",
    "panic",
    "recover",
    "print",
    "println",
    "close",
    "copy",
    "complex",
    "real",
    "imag",
    "min",
    "max",
    "clear",
]);

export const GO_STDLIB_NOISE: ReadonlySet<string> = new Set([
    "fmt",
    "log",
    "errors",
    "strconv",
    "strings",
    "bytes",
    "os",
    "io",
    "time",
    "math",
    "sort",
    "unicode",
    "utf8",
    "filepath",
    "path",
    "reflect",
    "runtime",
    "regexp",
    "bufio",
    "bloom",
]);

export const GO_MODULE_FILE = "go.mod";
export const GO_SOURCE_SUFFIX = ".go";
export const GO_TEST_SUFFIX = "_test.go";
export const GO_ENTRY = "main";
