const DOMAIN_ENTRIES: readonly (readonly [string, readonly string[]])[] = [
    ["ai", ["llm-inference", "agents-orchestration", "prompt-engineering", "embeddings-rag", "speech", "ml-models"]],
    [
        "commerce",
        [
            "payments",
            "billing",
            "subscriptions",
            "refunds",
            "coupons-promotions",
            "vouchers",
            "checkout",
            "invoicing",
            "savings",
            "financial-guarantees",
            "pricing",
        ],
    ],
    ["communication", ["transactional-email", "notifications", "messaging", "voice", "chat"]],
    ["content", ["internationalization", "copywriting-strings", "cms", "rich-text", "templating"]],
    ["data", ["persistence", "caching", "storage", "search-indexing", "data-modeling", "backup"]],
    [
        "developer-tooling",
        ["linting-quality", "documentation-generation", "code-generation", "testing", "build-tooling", "cli"],
    ],
    ["devops", ["deployment", "ci-cd", "release-management", "provisioning", "containerization"]],
    [
        "frontend-ui",
        [
            "components",
            "dom-construction",
            "layout",
            "animation",
            "forms",
            "accessibility",
            "state-management",
            "navigation",
        ],
    ],
    [
        "infrastructure",
        [
            "runtime-lifecycle",
            "task-scheduling",
            "resilience",
            "graceful-shutdown",
            "service-discovery",
            "workflow-orchestration",
            "event-streaming",
        ],
    ],
    ["marketing", ["email-marketing", "campaigns", "crm", "lead-management", "marketing-consent", "seo", "growth"]],
    [
        "media",
        [
            "audio",
            "video",
            "speech-to-text",
            "text-to-speech",
            "image-processing",
            "graphics-rendering",
            "mesh-geometry",
            "canvas",
            "visualization",
        ],
    ],
    ["networking", ["http-client", "proxying", "websockets", "api-gateway", "transport", "cookies"]],
    [
        "observability",
        [
            "logging",
            "metrics",
            "tracing",
            "health-monitoring",
            "alerting",
            "telemetry",
            "analytics",
            "activity-tracking",
        ],
    ],
    [
        "platform",
        ["system-info", "user-agent", "os-integration", "file-system", "process-management", "diffing", "utilities"],
    ],
    ["product", ["feature-flags", "onboarding", "roadmap", "gamification", "personalization", "preferences"]],
    [
        "security",
        [
            "encryption",
            "secrets-management",
            "input-sanitization",
            "content-security-policy",
            "rate-limiting",
            "authentication",
            "authorization",
            "session-management",
            "password-policy",
            "privacy-consent",
            "data-retention",
            "audit-logging",
            "vulnerability-scanning",
        ],
    ],
];

export const DOMAIN_TAXONOMY: Readonly<Record<string, readonly string[]>> = Object.fromEntries(DOMAIN_ENTRIES);
