export const AMERICAN_WORDS: Readonly<Record<string, string>> = {
    analyse: "analyze",
    analysed: "analyzed",
    analysing: "analyzing",
    artefact: "artifact",
    artefacts: "artifacts",
    behaviour: "behavior",
    behavioural: "behavioral",
    behaviours: "behaviors",
    cancelled: "canceled",
    catalogue: "catalog",
    catalogues: "catalogs",
    centre: "center",
    centres: "centers",
    channelled: "channeled",
    channelling: "channeling",
    colour: "color",
    colours: "colors",
    defence: "defense",
    equalled: "equaled",
    equalling: "equaling",
    favour: "favor",
    favoured: "favored",
    favours: "favors",
    fulfil: "fulfill",
    grey: "gray",
    honour: "honor",
    honoured: "honored",
    honouring: "honoring",
    honours: "honors",
    humour: "humor",
    judgement: "judgment",
    judgements: "judgments",
    labelled: "labeled",
    labelling: "labeling",
    labour: "labor",
    laboured: "labored",
    labours: "labors",
    licence: "license",
    licences: "licenses",
    marshalled: "marshaled",
    marshalling: "marshaling",
    modelled: "modeled",
    modelling: "modeling",
    neighbour: "neighbor",
    neighbouring: "neighboring",
    neighbours: "neighbors",
    offence: "offense",
    panelled: "paneled",
    practise: "practice",
    practised: "practiced",
    practises: "practices",
    practising: "practicing",
    rigour: "rigor",
    rumour: "rumor",
    rumours: "rumors",
    signalled: "signaled",
    signalling: "signaling",
    travelled: "traveled",
    travelling: "traveling",
};

export const PLURAL_SUFFIX = "s";

export const PLURAL_KEPT_AFTER: ReadonlySet<string> = new Set(["i", "s", "u"]);

export const PLURAL_MINIMUM_LENGTH = 4;

export const PLURAL_IES: readonly [string, string] = ["ies", "y"];

export const IZE_STEMS: readonly string[] = [
    "apolog",
    "author",
    "camel",
    "canonical",
    "capital",
    "categor",
    "central",
    "character",
    "custom",
    "emphas",
    "external",
    "final",
    "formal",
    "general",
    "hypothes",
    "initial",
    "institutional",
    "local",
    "material",
    "maxim",
    "memor",
    "minim",
    "normal",
    "optim",
    "organ",
    "parameter",
    "priorit",
    "real",
    "recogn",
    "sanit",
    "serial",
    "special",
    "stabil",
    "standard",
    "summar",
    "util",
    "visual",
];

export const SPELLING_PREFIXES: readonly string[] = [
    "anti",
    "co",
    "de",
    "dis",
    "mis",
    "non",
    "over",
    "pre",
    "re",
    "un",
    "under",
];

export const IZE_SUFFIXES: Readonly<Record<string, string>> = {
    isable: "izable",
    isably: "izably",
    isation: "ization",
    isations: "izations",
    ise: "ize",
    ised: "ized",
    iser: "izer",
    isers: "izers",
    ises: "izes",
    ising: "izing",
};
