export const HTMLHINT_DESCRIPTIONS: ReadonlyMap<string, string> = new Map([
    ["alt-require", "img elements must have an alt attribute"],
    ["attr-lowercase", "Attribute names must be lowercase"],
    ["attr-no-duplication", "No duplicate attributes on an element"],
    ["attr-unsafe-chars", "No unsafe characters in attribute values"],
    ["attr-value-double-quotes", "Attribute values must be double-quoted"],
    ["attr-value-not-empty", "Attributes must have a value"],
    ["doctype-first", "Doctype must be the first line"],
    ["doctype-html5", "Doctype must be html5"],
    ["head-script-disabled", "script tags are disabled in the head"],
    ["id-class-ad-disabled", "No ad-related id/class names"],
    ["id-unique", "id attributes must be unique"],
    ["inline-script-disabled", "Inline script is disabled (CSP)"],
    ["inline-style-disabled", "Inline style attributes are disabled (CSP)"],
    ["space-tab-mixed-disabled", "No mixed spaces and tabs"],
    ["spec-char-escape", "Special characters must be escaped"],
    ["src-not-empty", "src attributes must not be empty"],
    ["style-disabled", "style tags are disabled"],
    ["tag-pair", "Tags must be paired"],
    ["tagname-lowercase", "Tag names must be lowercase"],
    ["title-require", "The head must contain a title"],
]);

export const HTMLHINT_CANONICAL: ReadonlyMap<string, readonly string[]> = new Map([
    ["alt-require", ["accessibility"]],
    ["attr-unsafe-chars", ["security"]],
    ["head-script-disabled", ["security", "csp"]],
    ["id-unique", ["correctness"]],
    ["inline-script-disabled", ["security", "csp"]],
    ["inline-style-disabled", ["security", "css"]],
    ["spec-char-escape", ["security"]],
    ["tag-pair", ["correctness"]],
    ["title-require", ["accessibility"]],
]);
