import type { GrammarSource } from "#types/grammar.types";

export const GRAMMAR_SOURCES: readonly GrammarSource[] = [
    { lang: "bash", npm: "tree-sitter-bash" },
    { lang: "c", npm: "tree-sitter-c" },
    { lang: "c_sharp", npm: "tree-sitter-c-sharp" },
    { lang: "cpp", npm: "tree-sitter-cpp" },
    { lang: "css", npm: "tree-sitter-css" },
    { lang: "dart", npm: "tree-sitter-dart" },
    { lang: "elisp", npm: "tree-sitter-elisp" },
    { git: "https://github.com/elixir-lang/tree-sitter-elixir", lang: "elixir" },
    { lang: "elm", npm: "@elm-tooling/tree-sitter-elm" },
    { lang: "go", npm: "tree-sitter-go" },
    { lang: "html", npm: "tree-sitter-html" },
    { lang: "java", npm: "tree-sitter-java" },
    { lang: "javascript", npm: "tree-sitter-javascript" },
    { lang: "json", npm: "tree-sitter-json" },
    { lang: "kotlin", npm: "@tree-sitter-grammars/tree-sitter-kotlin" },
    { lang: "lua", npm: "@tree-sitter-grammars/tree-sitter-lua" },
    { lang: "objc", npm: "tree-sitter-objc" },
    { git: "https://github.com/tree-sitter/tree-sitter-ocaml", lang: "ocaml", subdir: "grammars/ocaml" },
    { lang: "php", npm: "tree-sitter-php", subdir: "php" },
    { lang: "python", npm: "tree-sitter-python" },
    { git: "https://github.com/rescript-lang/tree-sitter-rescript", lang: "rescript" },
    { lang: "ruby", npm: "tree-sitter-ruby" },
    { lang: "rust", npm: "tree-sitter-rust" },
    { lang: "scala", npm: "tree-sitter-scala" },
    { lang: "solidity", npm: "tree-sitter-solidity" },
    { lang: "swift", npm: "tree-sitter-swift" },
    { lang: "toml", npm: "@tree-sitter-grammars/tree-sitter-toml" },
    { lang: "typescript", npm: "tree-sitter-typescript", subdir: "typescript" },
    { lang: "tsx", npm: "tree-sitter-typescript", subdir: "tsx" },
    { lang: "yaml", npm: "@tree-sitter-grammars/tree-sitter-yaml" },
    { lang: "zig", npm: "@tree-sitter-grammars/tree-sitter-zig" },
    { lang: "sql", npm: "@derekstride/tree-sitter-sql" },
    { git: "https://github.com/sogaiu/tree-sitter-clojure", lang: "clojure" },
    { git: "https://github.com/r-lib/tree-sitter-r", lang: "r" },
];
