export {
    ALGO_DOMAIN_FACE,
    ALGO_FACE,
    ARCH_CATEGORY_FACE,
    ARCH_FACE,
    AXIS_RELATION,
    CATEGORY_RELATION,
    COMPOSED_BY_RELATION,
    COMPOSES_RELATION,
    CONFLICTS_WITH_RELATION,
    CONTRACTS_RELATION,
    CONTRACT_RELATION,
    DERIVED_BY_RELATION,
    DETECTS_RELATION,
    ENABLES_RELATION,
    FACE_SEPARATOR,
    FORCE_FACE,
    GROUNDED_BY_RELATION,
    GROUNDS_RELATION,
    KIND_FACE,
    LAYER_FACE,
    LEX_CATEGORY_FACE,
    LEX_FACE,
    ONTOLOGY_FACES,
    PAG_FACE,
    PRINCIPLE_RELATION,
    REASON_FACE,
    REFACTORED_BY_RELATION,
    REFACTORS_RELATION,
    REFERENCED_BY_RELATION,
    REINFORCES_RELATION,
    RELATION_FACE,
    REQUIRES_RELATION,
    STAGE_FACE,
    STAGE_RELATION,
    TENSIONS_RELATION,
    TENSIONS_WITH_RELATION,
    TENSION_FACE,
    TERM_RELATION,
    VIOLATED_BY_RELATION,
    VIOLATES_RELATION,
    VOCABULARY_FACE,
} from "./configuration/constants/ontology.constants.ts";
export {
    AMERICAN_WORDS,
    IZE_STEMS,
    IZE_SUFFIXES,
    PLURAL_IES,
    PLURAL_KEPT_AFTER,
    PLURAL_MINIMUM_LENGTH,
    PLURAL_SUFFIX,
    SPELLING_PREFIXES,
} from "./configuration/constants/word.constants.ts";
export { americanOf, normalizeWord } from "./core/normalizers/word.normalizer.ts";
export { identifierParts } from "./core/lexers/identifier.lexer.ts";
export { DIGITS, LOWER_ALPHA, UPPER_ALPHA, WHITESPACE } from "./configuration/constants/character.constants.ts";
export {
    everyChar,
    isAlpha,
    isDigit,
    isIdentifierChar,
    isLowerAlpha,
    isUpperAlpha,
    isWhitespace,
} from "./core/predicates/character.predicate.ts";
