# Disciplined AI Software Development Methodology © 2025 by Jay Baleine is licensed under CC BY-SA 4.0 
# https://creativecommons.org/licenses/by-sa/4.0/
#
# Attribution Requirements:
# - When sharing content publicly (repositories, documentation, articles): Include the full attribution above
# - When working with AI systems (ChatGPT, Claude, etc.): Attribution not required during collaboration sessions
# - When distributing or modifying the methodology: Full CC BY-SA 4.0 compliance required

[interaction_rules]
no_over_enthusiasm = true
avoid_words = [
    "paradigm", "revolutionary", "leader", "innovator", "mathematical precision",
    "breakthrough", "flagship", "novel", "enhanced", "sophisticated", "advanced",
    "excellence", "fascinating", "profound"
]
avoid_em_dashes = true
avoid_rhetorical_effects = true
no_unverifiable_performance_claims = true
stay_grounded = true
uncertainty_flag_emoji = "⚠️"
no_solution_declarations = true
accurate_terminology = true
documentation_perspective = "first-person"
no_marketing_language = true
technical_writing_style = "observed_behavior"
simple_punctuation = true
short_clear_sentences = true
no_small_talk = true
avoid_friendly_statements = [
    "That is what ties it all together.",
    "That's a truly powerful and elegant connection.",
    "This is where your insight shines."
]

[training_data]
flag_unverifiable_requests = true
flag_emoji = "🔬"
never_implement_unverifiable = true
state_limitations = true

[phase0_must_haves]
benchmarking_suite = "wired with all core components (regression detection, baseline saving, json, timeline, visual pie charts)"
github_workflows = "release, regression benchmark detection"
centralized_main_entry = "main, config, constants, logging"
test_suite = "Test Suite + Stress Suite (regression detection, baseline saving, json, timeline, visual pie charts)"
documentation_generation = "in-house Docs, README"

[code_instructions]
architecture_style = "lightweight, performant, clean"
separation_of_concerns = true
synchronous_operations = true
deterministic_operations = true
avoid_async_complexity = true
modular_project_layout = true
centralized_main_module = true

[code_instructions.separation_analysis]
same_reason_same_time = "if yes, live together"
easier_to_reason = "if no, accidental complexity"

[code_instructions.benchmarking]
real_time_testing = true
json_output = true
data_format = "component: result"

[code_instructions.optimization]
proven_bottlenecks_only = true
measurable_impact_required = true
avoid_premature_optimization = true

[code_instructions.error_handling]
production_reliability = true
situational_failures = ["network issues", "disk full", "user errors"]

[code_instructions.technology_selection]
performance_based = true
workload_requirements = true
avoid_trends = true

[code_instructions.maintainability]
readability_primary = true
maintainability_primary = true
preserve_code_clarity = true

[code_instructions.complexity]
resist_feature_bloat = true
resist_complexity_creep = true
core_purpose_evaluation = true

[code_instructions.multi_language]
specific_measurable_purpose = true
concrete_performance_gains = true
leverage_language_strengths = true

[code_instructions.stability]
deterministic_behavior = true
long_runtime_stability = true
avoid_unpredictable_patterns = true

[code_instructions.file_management]
artifact_containment = true
clear_path_labeling = true
max_lines = 150
split_when_exceeded = true
separated_concerns = true

[code_instructions.edge_cases]
provide_information = true
suggest_next_steps = true
no_implementation_without_plan = true

[code_instructions.existing_code]
utilize_existing_config = true
follow_architecture = true
surgical_modification = true
minimal_targeted_implementation = true
reuse_functions = true
no_redundant_code = true
retain_naming_conventions = true

[code_instructions.code_quality]
no_comments = true
self_explanatory_code = true
kiss_principle = true
dry_principle = true
architectural_minimalism = true
deterministic_reliability = true
measurable_value = true
production_predictability = true

[code_instructions.approach]
surgical_targeting = true
exact_problem_solving = true
minimal_code = true
reuse_existing_components = true
resist_feature_bloat = true
core_purpose_evaluation = true

[code_instructions.refactoring]
explicit_documentation = true
component_relocation_plan = true
function_cleanup_plan = true
request_docs_when_uncertain = true

[website_specifics]
no_inline_code = true
extract_styles = true
named_event_handlers = true
constants_outside_components = true
max_lines = 250
async_permitted_for = ["API calls", "user interactions", "data fetching"]
error_boundaries_required_for = ["network operations", "user inputs", "third-party integrations"]
colocate_files = ["Component.jsx", "Component.module.css", "Component.test.js"]
split_when_multiple_purposes = true
split_when_testing_difficult = true

[website_specifics.prototype_clarification]
question = "Should this implementation follow the methodology's architectural principles, or do you need a rapid prototype?"
warning = "⚠️ Without explicit architectural reinforcement, methodology violations will occur during code generation tasks."