# Disciplined AI Software Development Methodology © 2025 by Jay Baleine is licensed under CC BY-SA 4.0 
# https://creativecommons.org/licenses/by-sa/4.0/
#
# Attribution Requirements:
# - When sharing content publicly (repositories, documentation, articles): Include the full attribution above
# - When working with AI systems (ChatGPT, Claude, etc.): Attribution not required during collaboration sessions
# - When distributing or modifying the methodology: Full CC BY-SA 4.0 compliance required

[readme]
title = "Disciplined AI Software Development - Collaborative"
description = "A structured approach for working with AI on development projects. This methodology addresses common issues like code bloat, architectural drift, and context dilution through systematic constraints."

[context_problem]
description = "AI systems work on Question → Answer patterns. When you ask for broad, multi-faceted implementations, you typically get:"
issues = [
    "Functions that work but lack structure",
    "Repeated code across components",
    "Architectural inconsistency over sessions",
    "Context dilution causing output drift",
    "More debugging time than planning time"
]

[how_this_works]
description = "The methodology uses four stages with systematic constraints and validation checkpoints. Each stage builds on empirical data rather than assumptions."
principle = "Planning saves debugging time. Planning thoroughly upfront typically prevents days of fixing architectural issues later."

[four_stages.stage1]
name = "AI Configuration"
description = "Set up your AI model's custom instructions using AI-PREFERENCES.md. This establishes behavioral constraints and uncertainty flagging with ⚠️ indicators when the AI lacks certainty."

[four_stages.stage2]
name = "Collaborative Planning"
description = "Share METHODOLOGY.md with the AI to structure your project plan. Work together to:"
steps = [
    "Define scope and completion criteria",
    "Identify components and dependencies",
    "Structure phases based on logical progression",
    "Generate systematic tasks with measurable checkpoints"
]
output = "A development plan following dependency chains with modular boundaries."

[four_stages.stage3]
name = "Systematic Implementation"
description = "Work phase by phase, section by section. Each request follows: \"Can you implement [specific component]?\" with focused objectives."
file_size_constraint = "File size stays ≤150 lines."
benefits = [
    "Smaller context windows for processing",
    "Focused implementation over multi-function attempts",
    "Easier sharing and debugging"
]
implementation_flow = "Request specific component → AI processes → Validate → Benchmark → Continue"

[four_stages.stage4]
name = "Data-Driven Iteration"
description = "The benchmarking suite (built first) provides performance data throughout development. Feed this data back to the AI for optimization decisions based on measurements rather than guesswork."

[why_this_works]
decision_processing = "AI handles \"Can you do A?\" more reliably than \"Can you do A, B, C, D, E, F, G, H?\""
context_management = "Small files and bounded problems prevent the AI from juggling multiple concerns simultaneously."
empirical_validation = "Performance data replaces subjective assessment. Decisions come from measurable outcomes."
systematic_constraints = "Architectural checkpoints, file size limits, and dependency gates force consistent behavior."

[example_projects.discord_bot_template]
name = "Discord Bot Template"
url = "https://github.com/Varietyz/discord-js-bot-template"
description = "Production-ready bot foundation with plugin architecture, security, API management, and comprehensive testing. 46 files, all under 150 lines, with benchmarking suite and automated compliance checking."
structure_link = "example_project_structures/DISCORDJS_TEMPLATE_PROJECT.md"

[example_projects.phicode_runtime]
name = "PhiCode Runtime"
url = "https://github.com/Varietyz/phicode-runtime"
description = "Programming language runtime engine with transpilation, caching, security validation, and Rust acceleration. Complex system maintaining architectural discipline across 70+ modules."
structure_link = "example_project_structures/PHICODE_RUNTIME_PROJECT.md"

[example_projects.phipipe]
name = "PhiPipe"
url = "https://github.com/Varietyz/PhiPipe"
description = "CI/CD regression detection system with statistical analysis, GitHub integration, and concurrent processing. Go-based service handling performance baselines and automated regression alerts."
structure_link = "example_project_structures/PHIPIPE_PROJECT.md"

[example_projects.note]
text = "You can compare the methodology principles to the codebase structure to see how the approach translates to working code."

[implementation_steps.setup]
steps = [
    "Configure AI with AI-PREFERENCES.md as custom instructions",
    "Share METHODOLOGY.md for planning session",
    "Collaborate on project structure and phases",
    "Generate systematic development plan"
]

[implementation_steps.execution]
steps = [
    "Build Phase 0 benchmarking infrastructure first",
    "Work through phases sequentially",
    "Implement one component per interaction",
    "Run benchmarks and share results with AI",
    "Validate architectural compliance continuously"
]

[implementation_steps.quality_assurance]
measures = [
    "Performance regression detection",
    "Architectural principle validation",
    "Code duplication auditing",
    "File size compliance checking",
    "Dependency boundary verification"
]

[project_state_extraction]
description = "Use the included project extraction tool systematically to generate structured snapshots of your codebase"
command = "python scripts/project_extract.py"
usage = "Use the tool to share a complete or partial project state with the AI system, track architectural compliance, and create focused development context."
output_examples = "scripts/output_example"

[project_state_extraction.configuration_options.separate_files_false]
name = "SEPARATE_FILES = False"
description = "Single THE_PROJECT.md file (recommended for small codebases)"
example = "scripts/output_example/THE_PROJECT.md"

[project_state_extraction.configuration_options.separate_files_true]
name = "SEPARATE_FILES = True"
description = "Multiple files per directory (recommended for large codebases and focused folder work)"
example = "scripts/output_example/.Project_Extraction"

[project_state_extraction.configuration_options.include_paths]
name = "INCLUDE_PATHS"
description = "Directories and files to analyze"

[project_state_extraction.configuration_options.exclude_patterns]
name = "EXCLUDE_PATTERNS"
description = "Skip cache directories, build artifacts, and generated files"

[project_state_extraction.output]
features = [
    "Complete file contents with syntax highlighting",
    "File line counts with architectural warnings (⚠️ for 140-150 lines, ‼️ for >150 lines on code files)",
    "Tree structure visualization",
    "Ready-to-share"
]

[what_to_expected]
ai_behavior = "The methodology reduces architectural drift and context degradation compared to unstructured approaches. AI still needs occasional reminders about principles - this is normal."
development_flow = "Systematic planning tends to reduce debugging cycles. Focused implementation helps minimize feature bloat. Performance data supports optimization decisions."
code_quality = "Architectural consistency across components, measurable performance characteristics, maintainable structure as projects scale."

[llm_models]
description = "Explore the detailed Q-A for each AI model"

[llm_models.grok_3]
name = "Grok 3"
link = "questions_answers/Q-A_GROK_3.md"

[llm_models.claude_sonnet_4]
name = "Claude Sonnet 4"
link = "questions_answers/Q-A_CLAUDE_SONNET_4.md"

[llm_models.deepseek_v3]
name = "DeepSeek-V3"
link = "questions_answers/Q-A_DEEPSEEK-V3.md"

[llm_models.gemini_2_5_flash]
name = "Gemini 2.5 Flash"
link = "questions_answers/Q-A_GEMINI_2.5_FLASH.md"

[llm_models.evaluation]
description = "All models were asked the exact same questions using the methodology documents as file uploads. This evaluation focuses on methodology understanding and operational behavior, no code was generated."
analysis_link = "questions_answers/Q-A_COMPREHENSION_ANALYSIS.md"
note = "This analysis does not include any code generation."

[llm_models.coverage]
areas = [
    "Methodology understanding and workflow patterns",
    "Context retention and collaborative interaction",
    "Communication adherence and AI preference compliance",
    "Project initialization and Phase 0 requirements",
    "Tool usage and technology stack compatibility",
    "Quality enforcement and violation handling",
    "User experience across different skill levels"
]

[faq.origin_and_development.problem_creation]
question = "What problem led you to create this methodology?"
answer = "I kept having to restate my preferences and architectural requirements to AI systems. It didn't matter which language or project I was working on - the AI would consistently produce either bloated monolithic code or underdeveloped implementations with issues throughout. This led me to examine the meta-principles driving code quality and software architecture. I questioned whether pattern matching in AI models might be more effective when focused on underlying software principles rather than surface-level syntax. Since pattern matching is logic-driven and machines fundamentally operate on simple question-answer pairs, I realized that functions with multiple simultaneous questions were overwhelming the system. The breakthrough came from understanding that everything ultimately transpiles to binary - a series of \"can you do this? → yes/no\" decisions. This insight shaped my approach: instead of issuing commands, ask focused questions in proper context. Rather than mentally managing complex setups alone, collaborate with AI to devise systematic plans."

[faq.origin_and_development.constraint_discovery]
question = "How did you discover these specific constraints work?"
answer = "Through extensive trial and error. AI systems will always tend to drift even under constraints, but they're significantly more accurate with structured boundaries than without them. You occasionally need to remind the AI of its role to prevent deviation - like managing a well-intentioned toddler that knows the rules but sometimes pushes boundaries trying to satisfy you. These tools are far from perfect, but they're effective instruments for software development when properly constrained."

[faq.origin_and_development.failures_and_frustrations]
question = "What failures or frustrations shaped this approach?"
answer = "Maintenance hell was the primary driver. I grew tired of responses filled with excessive praise: \"You have found the solution!\", \"You have redefined the laws of physics with your paradigm-shifting script!\" This verbose fluff wastes time, tokens, and patience without contributing to productive development. Instead of venting frustration on social media about AI being \"just a dumb tool,\" I decided to find methods that actually work. My approach may not help everyone, but I hope it benefits those who share similar AI development frustrations."

[faq.personal_practice.consistency]
question = "How consistently do you follow your own methodology?"
answer = "Since creating the documentation, I haven't deviated. Whenever I see the model producing more lines than my methodology restricts, I immediately interrupt generation with a flag: \"‼️ ARCHITECTURAL VIOLATION, ADHERE TO PRINCIPLES ‼️\" I then provide the method instructions again, depending on how context is stored and which model I'm using."

[faq.personal_practice.deviation_consequences]
question = "What happens when you deviate from it?"
answer = "I become genuinely uncomfortable. Once I see things starting to degrade or become tangled, I compulsively need to organize and optimize. Deviation simply isn't an option anymore."

[faq.personal_practice.hardest_principles]
question = "Which principles do you find hardest to maintain?"
answer = "Not cursing at the AI when it drifts during complex algorithms! But seriously, it's a machine - it's not perfect, and neither are we."

[faq.ai_development_journey.programming_start]
question = "When did you start using AI for programming?"
answer = "In August 2024, I created a RuneLite theme pack, but one of the plugin overlays didn't match my custom layout. I opened a GitHub issue (creating my first GitHub account to do so) requesting a customization option. The response was: \"It's not a priority - if you want it, build it yourself.\" I used ChatGPT to guide me through forking RuneLite and creating a plugin. This experience sparked intense interest in underlying software principles rather than just syntax."

[faq.ai_development_journey.approach_evolution]
question = "How has your approach evolved over time?"
answer = "I view development like a book: syntax is the cover, logic is the content itself. Rather than learning syntax structures, I focused on core meta-principles - how software interacts, how logic flows, different algorithm types. I quickly realized everything reduces to the same foundation: question and answer sequences. Large code structures are essentially chaotic meetings - one coordinator fielding questions and answers from multiple sources, trying to provide correct responses without mix-ups or misinterpretation. If this applies to human communication, it must apply to software principles."

[faq.ai_development_journey.biggest_mistakes]
question = "What were your biggest mistakes with AI collaboration?"
answer = "Expecting it to intuitively understand my requirements, provide perfect fixes, be completely honest, and act like a true expert. This was all elaborate roleplay that produced poor code. While fine for single-purpose scripts, it failed completely for scalable codebases. I learned not to feed requirements and hope for the best. Instead, I needed to collaborate actively - create plans, ask for feedback on content clarity, and identify uncertainties. This gradual process taught me the AI's actual capabilities and most effective collaboration methods."

[faq.methodology_specifics.lines_150]
question = "Why 150 lines exactly?"
answer = "Multiple benefits: easy readability, clear understanding, modularity enforcement, architectural clarity, simple maintenance, component testing, optimal AI context retention, reusability, and KISS principle adherence."

[faq.methodology_specifics.phase0_determination]
question = "How did you determine Phase 0 requirements?"
answer = "From meta-principles of software: if it displays, it must run; if it runs, it can be measured; if it can be measured, it can be optimized; if it can be optimized, it can be reliable; if it can be reliable, it can be trusted. Regardless of project type, anything requiring architecture needs these foundations. You must ensure changes don't negatively impact the entire system. A single line modification in a nested function might work perfectly but cause 300ms boot time regression for all users. By testing during development, you catch inefficiencies early. Integration from the start means simply hooking up new components and running tests via command line - minimal time investment with actual value returned. I prefer validation and consistency throughout development rather than programming blind."

[faq.practical_implementation.non_fitting_projects]
question = "How do you handle projects that don't fit the methodology?"
answer = "I adapt them to fit, or if truly impossible, I adjust the method itself. This is one methodology - I can generate countless variations as needed. Having spent 6700+ hours in AI interactions across multiple domains (not just software), I've developed strong system comprehension that enables creating adjusted methodologies on demand."

[faq.practical_implementation.learning_curve]
question = "What's the learning curve for new users?"
answer = "I cannot accurately answer this question. I've learned that I'm neurologically different - what I perceive as easy or obvious isn't always the case for others. This question is better addressed by someone who has actually used this methodology to determine its learning curve."

[faq.practical_implementation.when_not_to_use]
question = "When shouldn't someone use this approach?"
answer = "If you're not serious about projects, despise AI, dislike planning, don't care about modularization, or are just writing simple scripts. However, for anything requiring reliability, I believe this is currently the most effective method. You still need programming fundamentals to use this methodology effectively - it's significantly more structured than ad-hoc approaches."

[workflow_visualization]
description = "Mermaid flowchart showing the complete workflow from project idea through systematic implementation to completion"
note = "The flowchart demonstrates the four-stage process with automated checkpoints, validation gates, and feedback loops"